#!/usr/bin/env python3
"""Generate Phase 2 minimum Brassdeep content JSON under game/content/."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "game" / "content"

# ---------------------------------------------------------------------------
# Content definitions
# ---------------------------------------------------------------------------

RACES: list[dict[str, Any]] = [
    {
        "id": "race_human",
        "name": "Human",
        "description": "Adaptable surface folk with balanced training and no glaring weaknesses.",
        "base_hp": 22,
        "melee_accuracy": 50,
        "melee_damage": 2,
        "ranged_accuracy": 48,
        "ranged_damage": 2,
        "defense": 1,
        "engineering": 1,
        "marksmanship": 1,
        "smithing": 1,
        "medicine": 1,
        "stealth": 1,
        "occult": 0,
        "resistances": {"poison": 0, "fear": 0, "steam": 0},
        "skill_affinities": {"skill_medicine": 0.9, "skill_defense": 0.95},
        "starting_items": [{"item_id": "item_field_ration", "count": 2}],
        "forbidden_slots": [],
        "passives": ["passive_adaptable"],
    },
    {
        "id": "race_automaton",
        "name": "Automaton",
        "description": "Clockwork body; resilient plating and innate engineering, but poor occult attunement.",
        "base_hp": 26,
        "melee_accuracy": 48,
        "melee_damage": 3,
        "ranged_accuracy": 42,
        "ranged_damage": 2,
        "defense": 2,
        "engineering": 3,
        "marksmanship": 0,
        "smithing": 2,
        "medicine": 0,
        "stealth": -1,
        "occult": -2,
        "resistances": {"poison": 50, "fear": 25, "steam": 10},
        "skill_affinities": {"skill_engineering": 0.75, "skill_smithing": 0.85, "skill_occult": 1.4},
        "starting_items": [{"item_id": "item_machine_oil", "count": 1}],
        "forbidden_slots": [],
        "passives": ["passive_oil_blood"],
    },
    {
        "id": "race_dwarf",
        "name": "Dwarf",
        "description": "Stocky forge-born miners with heavy armor affinity and stubborn constitution.",
        "base_hp": 24,
        "melee_accuracy": 52,
        "melee_damage": 3,
        "ranged_accuracy": 40,
        "ranged_damage": 1,
        "defense": 3,
        "engineering": 1,
        "marksmanship": 0,
        "smithing": 3,
        "medicine": 0,
        "stealth": -2,
        "occult": 0,
        "resistances": {"poison": 10, "fear": 15, "steam": 5},
        "skill_affinities": {"skill_smithing": 0.7, "skill_defense": 0.8, "skill_stealth": 1.3},
        "starting_items": [{"item_id": "item_coal", "count": 3}],
        "forbidden_slots": [],
        "passives": ["passive_stonehide"],
    },
    {
        "id": "race_elf",
        "name": "Elf",
        "description": "Keen-eyed marksmen and silent scouts; fragile but precise at range.",
        "base_hp": 18,
        "melee_accuracy": 48,
        "melee_damage": 1,
        "ranged_accuracy": 58,
        "ranged_damage": 2,
        "defense": 0,
        "engineering": 0,
        "marksmanship": 3,
        "smithing": 0,
        "medicine": 1,
        "stealth": 3,
        "occult": 1,
        "resistances": {"poison": 5, "fear": 10, "steam": 0},
        "skill_affinities": {"skill_marksmanship": 0.75, "skill_stealth": 0.8, "skill_smithing": 1.25},
        "starting_items": [{"item_id": "item_carbine", "count": 1}, {"item_id": "item_rifle_ammo", "count": 12}],
        "forbidden_slots": [],
        "passives": ["passive_keen_senses"],
    },
    {
        "id": "race_gnome",
        "name": "Gnome",
        "description": "Inventive tinkerers with medical training; poor melee brawlers.",
        "base_hp": 17,
        "melee_accuracy": 42,
        "melee_damage": 0,
        "ranged_accuracy": 46,
        "ranged_damage": 1,
        "defense": 0,
        "engineering": 3,
        "marksmanship": 1,
        "smithing": 1,
        "medicine": 3,
        "stealth": 1,
        "occult": 1,
        "resistances": {"poison": 0, "fear": 5, "steam": 0},
        "skill_affinities": {"skill_engineering": 0.8, "skill_medicine": 0.75, "skill_melee": 1.35},
        "starting_items": [{"item_id": "item_healing_salve", "count": 2}, {"item_id": "item_gears", "count": 2}],
        "forbidden_slots": [],
        "passives": ["passive_tinker"],
    },
    {
        "id": "race_beastfolk",
        "name": "Beastfolk",
        "description": "Feral tunnel hunters with natural melee prowess and pack instincts.",
        "base_hp": 21,
        "melee_accuracy": 54,
        "melee_damage": 3,
        "ranged_accuracy": 38,
        "ranged_damage": 1,
        "defense": 1,
        "engineering": -1,
        "marksmanship": 0,
        "smithing": 0,
        "medicine": 0,
        "stealth": 2,
        "occult": 0,
        "resistances": {"poison": 15, "fear": -10, "steam": 0},
        "skill_affinities": {"skill_melee": 0.8, "skill_stealth": 0.85, "skill_engineering": 1.4},
        "starting_items": [{"item_id": "item_bayonet", "count": 1}],
        "forbidden_slots": [],
        "passives": ["passive_pack_hunter"],
    },
]

CLASSES: list[dict[str, Any]] = [
    {
        "id": "class_adventurer",
        "name": "Adventurer",
        "description": "Generalist explorer of the deep with modest bonuses everywhere.",
        "hp_bonus": 2,
        "melee_accuracy": 4,
        "melee_damage": 1,
        "ranged_accuracy": 2,
        "ranged_damage": 0,
        "defense": 1,
        "engineering": 0,
        "marksmanship": 1,
        "smithing": 0,
        "medicine": 1,
        "stealth": 1,
        "occult": 0,
        "skill_affinities": {},
        "starting_items": [{"item_id": "item_wrench", "count": 1}, {"item_id": "item_pepperbox", "count": 1}, {"item_id": "item_ball_ammo", "count": 12}],
        "starting_skills": {"skill_melee": 1, "skill_marksmanship": 1},
        "passives": ["passive_lucky_break"],
    },
    {
        "id": "class_engineer",
        "name": "Engineer",
        "description": "Tinker and craftsman of brass devices; excels at repairs and fabrication.",
        "hp_bonus": 0,
        "melee_accuracy": 0,
        "melee_damage": 0,
        "ranged_accuracy": 4,
        "ranged_damage": 1,
        "defense": 0,
        "engineering": 4,
        "marksmanship": 1,
        "smithing": 2,
        "medicine": 0,
        "stealth": 0,
        "occult": 0,
        "skill_affinities": {"skill_engineering": 0.8, "skill_smithing": 0.9},
        "starting_items": [{"item_id": "item_wrench", "count": 1}, {"item_id": "item_scrap", "count": 5}, {"item_id": "item_gears", "count": 2}],
        "starting_skills": {"skill_engineering": 2, "skill_smithing": 1},
        "passives": ["passive_field_repair"],
    },
    {
        "id": "class_gunslinger",
        "name": "Gunslinger",
        "description": "Marksman specializing in firearms, quick reloads, and crit shots.",
        "hp_bonus": 0,
        "melee_accuracy": 2,
        "melee_damage": 0,
        "ranged_accuracy": 8,
        "ranged_damage": 3,
        "defense": 0,
        "engineering": 0,
        "marksmanship": 4,
        "smithing": 0,
        "medicine": 0,
        "stealth": 1,
        "occult": 0,
        "skill_affinities": {"skill_marksmanship": 0.75},
        "starting_items": [{"item_id": "item_pepperbox", "count": 1}, {"item_id": "item_rifle", "count": 1}, {"item_id": "item_ball_ammo", "count": 18}, {"item_id": "item_rifle_ammo", "count": 12}],
        "starting_skills": {"skill_marksmanship": 3},
        "passives": ["passive_quickdraw"],
    },
    {
        "id": "class_occultist",
        "name": "Occultist",
        "description": "Scholar of forbidden steam-rites; resists fear and channels eldritch force.",
        "hp_bonus": -2,
        "melee_accuracy": 0,
        "melee_damage": 0,
        "ranged_accuracy": 2,
        "ranged_damage": 1,
        "defense": 0,
        "engineering": 1,
        "marksmanship": 0,
        "smithing": 0,
        "medicine": 1,
        "stealth": 2,
        "occult": 4,
        "skill_affinities": {"skill_occult": 0.7, "skill_medicine": 0.95},
        "starting_items": [{"item_id": "item_arc_pistol", "count": 1}, {"item_id": "item_arc_cell", "count": 6}, {"item_id": "item_crystal", "count": 1}],
        "starting_skills": {"skill_occult": 2, "skill_stealth": 1},
        "passives": ["passive_fear_resist"],
    },
    {
        "id": "class_officer",
        "name": "Officer",
        "description": "Disciplined commander with defensive training and rallying presence.",
        "hp_bonus": 4,
        "melee_accuracy": 3,
        "melee_damage": 2,
        "ranged_accuracy": 3,
        "ranged_damage": 1,
        "defense": 3,
        "engineering": 0,
        "marksmanship": 2,
        "smithing": 0,
        "medicine": 1,
        "stealth": 0,
        "occult": 0,
        "skill_affinities": {"skill_defense": 0.85},
        "starting_items": [{"item_id": "item_cutlass", "count": 1}, {"item_id": "item_brass_plate", "count": 1}, {"item_id": "item_brass_helm", "count": 1}],
        "starting_skills": {"skill_defense": 2, "skill_melee": 1},
        "passives": ["passive_rally"],
    },
    {
        "id": "class_scoundrel",
        "name": "Scoundrel",
        "description": "Back-alley operative favoring stealth, poisons, and opportunistic strikes.",
        "hp_bonus": 0,
        "melee_accuracy": 5,
        "melee_damage": 2,
        "ranged_accuracy": 2,
        "ranged_damage": 0,
        "defense": 0,
        "engineering": 0,
        "marksmanship": 1,
        "smithing": 0,
        "medicine": 0,
        "stealth": 4,
        "occult": 1,
        "skill_affinities": {"skill_stealth": 0.75, "skill_melee": 0.9},
        "starting_items": [{"item_id": "item_bayonet", "count": 1}, {"item_id": "item_smoke_bomb", "count": 2}, {"item_id": "item_leather_coat", "count": 1}],
        "starting_skills": {"skill_stealth": 2, "skill_melee": 1},
        "passives": ["passive_backstab"],
    },
]

SKILLS: list[dict[str, Any]] = [
    {
        "id": "skill_melee",
        "name": "Melee",
        "description": "Close combat accuracy, damage, and finishing techniques.",
        "family": "combat",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "power_strike",
                "name": "Power Strike",
                "description": "Heavy blow that adds burst melee damage.",
                "rank_required": 2,
                "effects": {"melee_damage": 2, "crit_chance": 5},
            },
            {
                "id": "cleave_ready",
                "name": "Cleave Ready",
                "description": "Improved follow-through on adjacent foes.",
                "rank_required": 4,
                "effects": {"melee_accuracy": 4, "cleave": True},
            },
        ],
    },
    {
        "id": "skill_marksmanship",
        "name": "Marksmanship",
        "description": "Firearm accuracy, reload speed, and ranged crits.",
        "family": "combat",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "improved_reload",
                "name": "Improved Reload",
                "description": "Faster chamber cycles between shots.",
                "rank_required": 1,
                "effects": {"reload_speed": 1, "ranged_accuracy": 2},
            },
            {
                "id": "steady_aim",
                "name": "Steady Aim",
                "description": "Brace for a precise long-range shot.",
                "rank_required": 3,
                "effects": {"ranged_accuracy": 6, "range_bonus": 1},
            },
            {
                "id": "crit_chance",
                "name": "Deadeye",
                "description": "Critical hit chance with firearms.",
                "rank_required": 5,
                "effects": {"crit_chance": 10, "ranged_damage": 1},
            },
        ],
    },
    {
        "id": "skill_defense",
        "name": "Defense",
        "description": "Armor use, blocking, and damage mitigation.",
        "family": "combat",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "defensive_stance",
                "name": "Defensive Stance",
                "description": "Brace to reduce incoming damage.",
                "rank_required": 2,
                "effects": {"defense": 3, "block_chance": 10},
            },
            {
                "id": "fear_resist",
                "name": "Iron Nerves",
                "description": "Resist fear and panic effects.",
                "rank_required": 3,
                "effects": {"fear_resist": 25},
            },
        ],
    },
    {
        "id": "skill_engineering",
        "name": "Engineering",
        "description": "Device operation, repairs, and steam tinkering.",
        "family": "craft",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "mechanical_repair",
                "name": "Mechanical Repair",
                "description": "Restore durability to gear and automata.",
                "rank_required": 2,
                "effects": {"repair_amount": 5, "engineering": 1},
            },
            {
                "id": "steam_tinker",
                "name": "Steam Tinker",
                "description": "Boost device output at the cost of heat.",
                "rank_required": 4,
                "effects": {"device_power": 2, "overheat_risk": True},
            },
        ],
    },
    {
        "id": "skill_smithing",
        "name": "Smithing",
        "description": "Forge weapons and armor with higher quality.",
        "family": "craft",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "craft_quality",
                "name": "Craft Quality",
                "description": "Crafted gear gains bonus stats.",
                "rank_required": 2,
                "effects": {"craft_bonus_damage": 1, "craft_bonus_defense": 1},
            },
        ],
    },
    {
        "id": "skill_medicine",
        "name": "Medicine",
        "description": "Healing, antidotes, and field triage.",
        "family": "support",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "medical_treatment",
                "name": "Medical Treatment",
                "description": "Consumable heals restore extra HP.",
                "rank_required": 2,
                "effects": {"heal_bonus": 4, "medicine": 1},
            },
        ],
    },
    {
        "id": "skill_stealth",
        "name": "Stealth",
        "description": "Silent movement and ambush techniques.",
        "family": "support",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "stealth_step",
                "name": "Stealth Step",
                "description": "Move quietly past distant sentries.",
                "rank_required": 2,
                "effects": {"stealth": 2, "noise_reduction": 1},
            },
            {
                "id": "shadow_strike",
                "name": "Shadow Strike",
                "description": "Ambush attacks deal bonus damage.",
                "rank_required": 4,
                "effects": {"ambush_damage": 3, "stealth": 1},
            },
        ],
    },
    {
        "id": "skill_occult",
        "name": "Occult",
        "description": "Forbidden rites, fear manipulation, and arc discharge.",
        "family": "arcane",
        "max_rank": 5,
        "base_cost": 1,
        "cost_growth": 1,
        "abilities": [
            {
                "id": "ward_whisper",
                "name": "Ward Whisper",
                "description": "Brief ward against steam and poison.",
                "rank_required": 2,
                "effects": {"poison_resist": 15, "steam_resist": 10},
            },
        ],
    },
]

ITEMS: list[dict[str, Any]] = [
    # --- melee (mainhand) ---
    {
        "id": "item_wrench",
        "name": "Brass Wrench",
        "description": "A heavy adjustable wrench for tight bolts and skulls.",
        "equip_slot": "mainhand",
        "damage": 2,
        "accuracy": 2,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 3,
        "value": 8,
        "category": "weapon",
        "allowed_affixes": ["affix_balanced", "affix_heavy"],
        "is_ammo": False,
    },
    {
        "id": "item_cutlass",
        "name": "Officer's Cutlass",
        "description": "Curved naval blade favored by brassdeep officers.",
        "equip_slot": "mainhand",
        "damage": 3,
        "accuracy": 3,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 2,
        "value": 18,
        "category": "weapon",
        "allowed_affixes": ["affix_sharp", "affix_balanced", "affix_serrated"],
        "is_ammo": False,
    },
    {
        "id": "item_warhammer",
        "name": "Forge Warhammer",
        "description": "Two-handed striking tool that dents plate armor.",
        "equip_slot": "mainhand",
        "damage": 5,
        "accuracy": 1,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 5,
        "value": 22,
        "category": "weapon",
        "allowed_affixes": ["affix_heavy", "affix_reinforced"],
        "is_ammo": False,
    },
    {
        "id": "item_bayonet",
        "name": "Socket Bayonet",
        "description": "Knife bayonet for close quarters when powder runs dry.",
        "equip_slot": "mainhand",
        "damage": 2,
        "accuracy": 4,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 1,
        "value": 10,
        "category": "weapon",
        "allowed_affixes": ["affix_sharp", "affix_poisoned"],
        "is_ammo": False,
    },
    {
        "id": "item_steam_axe",
        "name": "Steam Axe",
        "description": "Piston-assisted axe that vents scalding steam on impact.",
        "equip_slot": "mainhand",
        "damage": 4,
        "accuracy": 2,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 4,
        "value": 28,
        "category": "weapon",
        "allowed_affixes": ["affix_steamcharged", "affix_heavy"],
        "is_ammo": False,
    },
    # --- firearms (ranged) ---
    {
        "id": "item_pepperbox",
        "name": "Pepperbox Pistol",
        "description": "Multi-barrel black-powder sidearm.",
        "equip_slot": "ranged",
        "damage": 3,
        "accuracy": 1,
        "defense": 0,
        "range_tiles": 5,
        "max_stack": 1,
        "weight": 2,
        "value": 20,
        "category": "firearm",
        "ammo_type": "ball",
        "allowed_affixes": ["affix_accurate", "affix_quickdraw"],
        "is_ammo": False,
    },
    {
        "id": "item_rifle",
        "name": "Brass Rifle",
        "description": "Long-barrel rifle accurate at tunnel range.",
        "equip_slot": "ranged",
        "damage": 4,
        "accuracy": 3,
        "defense": 0,
        "range_tiles": 8,
        "max_stack": 1,
        "weight": 4,
        "value": 35,
        "category": "firearm",
        "ammo_type": "rifle",
        "allowed_affixes": ["affix_accurate", "affix_calibrated"],
        "is_ammo": False,
    },
    {
        "id": "item_shotgun",
        "name": "Coach Shotgun",
        "description": "Short scattergun devastating at close range.",
        "equip_slot": "ranged",
        "damage": 5,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 4,
        "max_stack": 1,
        "weight": 4,
        "value": 30,
        "category": "firearm",
        "ammo_type": "shell",
        "allowed_affixes": ["affix_heavy", "affix_reinforced"],
        "is_ammo": False,
    },
    {
        "id": "item_arc_pistol",
        "name": "Arc Pistol",
        "description": "Occult-charged sidearm firing crackling arc cells.",
        "equip_slot": "ranged",
        "damage": 3,
        "accuracy": 2,
        "defense": 0,
        "range_tiles": 6,
        "max_stack": 1,
        "weight": 2,
        "value": 40,
        "category": "firearm",
        "ammo_type": "arc",
        "allowed_affixes": ["affix_occultbound", "affix_steamcharged"],
        "is_ammo": False,
    },
    {
        "id": "item_carbine",
        "name": "Scout Carbine",
        "description": "Light carbine for mobile marksmen.",
        "equip_slot": "ranged",
        "damage": 3,
        "accuracy": 2,
        "defense": 0,
        "range_tiles": 7,
        "max_stack": 1,
        "weight": 3,
        "value": 28,
        "category": "firearm",
        "ammo_type": "rifle",
        "allowed_affixes": ["affix_balanced", "affix_quickdraw"],
        "is_ammo": False,
    },
    # --- ammo ---
    {
        "id": "item_ball_ammo",
        "name": "Lead Balls",
        "description": "Ammunition for pepperbox pistols.",
        "equip_slot": "ammo",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 30,
        "weight": 0,
        "value": 1,
        "category": "ammo",
        "is_ammo": True,
        "ammo_for": "ball",
        "allowed_affixes": [],
    },
    {
        "id": "item_rifle_ammo",
        "name": "Rifle Cartridges",
        "description": "Full-power cartridges for rifles and carbines.",
        "equip_slot": "ammo",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 24,
        "weight": 0,
        "value": 2,
        "category": "ammo",
        "is_ammo": True,
        "ammo_for": "rifle",
        "allowed_affixes": [],
    },
    {
        "id": "item_shot_shells",
        "name": "Shot Shells",
        "description": "Paper shells packed with buckshot.",
        "equip_slot": "ammo",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 16,
        "weight": 0,
        "value": 2,
        "category": "ammo",
        "is_ammo": True,
        "ammo_for": "shell",
        "allowed_affixes": [],
    },
    {
        "id": "item_arc_cell",
        "name": "Arc Cell",
        "description": "Crystalline capacitor for arc pistols.",
        "equip_slot": "ammo",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 12,
        "weight": 0,
        "value": 5,
        "category": "ammo",
        "is_ammo": True,
        "ammo_for": "arc",
        "allowed_affixes": [],
    },
    # --- armor: head ---
    {
        "id": "item_brass_helm",
        "name": "Brass Helm",
        "description": "Riveted helmet with narrow visor slit.",
        "equip_slot": "head",
        "damage": 0,
        "accuracy": 0,
        "defense": 2,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 3,
        "value": 15,
        "category": "armor",
        "allowed_affixes": ["affix_reinforced", "affix_riveted"],
        "is_ammo": False,
    },
    {
        "id": "item_filter_mask",
        "name": "Filter Mask",
        "description": "Crafted respirator against steam toxins.",
        "equip_slot": "head",
        "damage": 0,
        "accuracy": 0,
        "defense": 1,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 1,
        "value": 12,
        "category": "armor",
        "allowed_affixes": ["affix_insulated"],
        "is_ammo": False,
    },
    {
        "id": "item_engineer_goggles",
        "name": "Engineer Goggles",
        "description": "Tinted lenses that reduce glare from forge light.",
        "equip_slot": "head",
        "damage": 0,
        "accuracy": 1,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 1,
        "value": 10,
        "category": "armor",
        "allowed_affixes": ["affix_calibrated"],
        "is_ammo": False,
    },
    # --- armor: body ---
    {
        "id": "item_brass_plate",
        "name": "Brass Plate",
        "description": "Oxidized breastplate over leather backing.",
        "equip_slot": "body",
        "damage": 0,
        "accuracy": 0,
        "defense": 3,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 5,
        "value": 25,
        "category": "armor",
        "allowed_affixes": ["affix_reinforced", "affix_riveted"],
        "is_ammo": False,
    },
    {
        "id": "item_leather_coat",
        "name": "Leather Coat",
        "description": "Oil-treated long coat that muffles movement.",
        "equip_slot": "body",
        "damage": 0,
        "accuracy": 0,
        "defense": 1,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 2,
        "value": 12,
        "category": "armor",
        "allowed_affixes": ["affix_padded", "affix_insulated"],
        "is_ammo": False,
    },
    {
        "id": "item_steam_vest",
        "name": "Steam Vest",
        "description": "Insulated vest with pressure-release valves.",
        "equip_slot": "body",
        "damage": 0,
        "accuracy": 0,
        "defense": 2,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 3,
        "value": 18,
        "category": "armor",
        "allowed_affixes": ["affix_insulated", "affix_steamcharged"],
        "is_ammo": False,
    },
    # --- armor: hands ---
    {
        "id": "item_work_gloves",
        "name": "Work Gloves",
        "description": "Thick gloves that improve grip on tools.",
        "equip_slot": "hands",
        "damage": 0,
        "accuracy": 1,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 1,
        "value": 6,
        "category": "armor",
        "allowed_affixes": ["affix_padded"],
        "is_ammo": False,
    },
    {
        "id": "item_padded_gauntlets",
        "name": "Padded Gauntlets",
        "description": "Quilted gauntlets that soften incoming blows.",
        "equip_slot": "hands",
        "damage": 0,
        "accuracy": 0,
        "defense": 1,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 2,
        "value": 10,
        "category": "armor",
        "allowed_affixes": ["affix_reinforced", "affix_riveted"],
        "is_ammo": False,
    },
    # --- armor: feet ---
    {
        "id": "item_iron_boots",
        "name": "Iron Boots",
        "description": "Heavy boots that protect against crushing debris.",
        "equip_slot": "feet",
        "damage": 0,
        "accuracy": 0,
        "defense": 2,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 3,
        "value": 14,
        "category": "armor",
        "allowed_affixes": ["affix_reinforced"],
        "is_ammo": False,
    },
    {
        "id": "item_soft_shoes",
        "name": "Soft Shoes",
        "description": "Felt-soled shoes for silent footfalls.",
        "equip_slot": "feet",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 1,
        "value": 8,
        "category": "armor",
        "allowed_affixes": ["affix_padded"],
        "is_ammo": False,
    },
    {
        "id": "item_steam_treads",
        "name": "Steam Treads",
        "description": "Mechanized treads that vent heat with each step.",
        "equip_slot": "feet",
        "damage": 0,
        "accuracy": 0,
        "defense": 1,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 3,
        "value": 20,
        "category": "armor",
        "allowed_affixes": ["affix_steamcharged", "affix_insulated"],
        "is_ammo": False,
    },
    # --- consumables ---
    {
        "id": "item_healing_salve",
        "name": "Healing Salve",
        "description": "Herbal poultice that closes wounds quickly.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 8,
        "weight": 0,
        "value": 6,
        "category": "consumable",
        "use_effect": "heal_8",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_machine_oil",
        "name": "Machine Oil",
        "description": "Restorative oil for flesh and gears alike.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 10,
        "weight": 0,
        "value": 5,
        "category": "consumable",
        "use_effect": "heal_5_oil",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_antidote_vial",
        "name": "Antidote Vial",
        "description": "Neutralizes common tunnel venoms.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 6,
        "weight": 0,
        "value": 8,
        "category": "consumable",
        "use_effect": "cure_poison",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_combat_stim",
        "name": "Combat Stim",
        "description": "Adrenal injection boosting accuracy briefly.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 4,
        "weight": 0,
        "value": 12,
        "category": "consumable",
        "use_effect": "stim_accuracy_6",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_field_ration",
        "name": "Field Ration",
        "description": "Preserved meal that restores stamina over time.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 10,
        "weight": 0,
        "value": 3,
        "category": "consumable",
        "use_effect": "heal_3_slow",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_smoke_bomb",
        "name": "Smoke Bomb",
        "description": "Sulfur charge that blankets an area in choking smoke.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 5,
        "weight": 0,
        "value": 10,
        "category": "consumable",
        "use_effect": "smoke_cloud",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    # --- materials ---
    {
        "id": "item_scrap",
        "name": "Scrap Metal",
        "description": "Twisted brass and iron fragments.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 20,
        "weight": 1,
        "value": 2,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_brass_ingot",
        "name": "Brass Ingot",
        "description": "Refined brass stock for plating and fittings.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 10,
        "weight": 2,
        "value": 6,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_gears",
        "name": "Clockwork Gears",
        "description": "Assorted pinions and mainsprings.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 15,
        "weight": 1,
        "value": 4,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_coal",
        "name": "Coal",
        "description": "Dense fuel for forges and boilers.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 20,
        "weight": 1,
        "value": 2,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_oil_can",
        "name": "Oil Can",
        "description": "Portable lubricant for crafting and maintenance.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 8,
        "weight": 1,
        "value": 4,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_sulfur",
        "name": "Sulfur",
        "description": "Yellow crystals used in powder and smoke devices.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 15,
        "weight": 0,
        "value": 3,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_herbs",
        "name": "Tunnel Herbs",
        "description": "Medicinal fungi and moss harvested from the deep.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 12,
        "weight": 0,
        "value": 3,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_leather",
        "name": "Tanned Leather",
        "description": "Flexible hide for coats and straps.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 10,
        "weight": 1,
        "value": 4,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_crystal",
        "name": "Occult Crystal",
        "description": "Resonant crystal that stores arc discharge.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 6,
        "weight": 0,
        "value": 12,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_wire",
        "name": "Copper Wire",
        "description": "Fine wire for bindings and electrical leads.",
        "equip_slot": "none",
        "damage": 0,
        "accuracy": 0,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 20,
        "weight": 0,
        "value": 2,
        "category": "material",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    # --- unique craft results ---
    {
        "id": "item_reinforced_wrench",
        "name": "Reinforced Wrench",
        "description": "Scrap-forged melee tool with a weighted head.",
        "equip_slot": "mainhand",
        "damage": 4,
        "accuracy": 2,
        "defense": 0,
        "range_tiles": 0,
        "max_stack": 1,
        "weight": 4,
        "value": 16,
        "category": "weapon",
        "allowed_affixes": [],
        "is_ammo": False,
    },
    {
        "id": "item_calibrated_pepperbox",
        "name": "Calibrated Pepperbox",
        "description": "Engineer-tuned firearm with tighter grouping.",
        "equip_slot": "ranged",
        "damage": 4,
        "accuracy": 3,
        "defense": 0,
        "range_tiles": 6,
        "max_stack": 1,
        "weight": 2,
        "value": 35,
        "category": "firearm",
        "ammo_type": "ball",
        "allowed_affixes": [],
        "is_ammo": False,
    },
]

AFFIXES: list[dict[str, Any]] = [
    {"id": "affix_balanced", "name_prefix": "Balanced", "description": "Better handling.", "damage": 0, "accuracy": 2, "defense": 0},
    {"id": "affix_accurate", "name_prefix": "Accurate", "description": "True aim.", "damage": 0, "accuracy": 3, "defense": 0},
    {"id": "affix_reinforced", "name_prefix": "Reinforced", "description": "Extra plating.", "damage": 0, "accuracy": 0, "defense": 2},
    {"id": "affix_sharp", "name_prefix": "Sharp", "description": "Keen edge.", "damage": 2, "accuracy": 1, "defense": 0},
    {"id": "affix_heavy", "name_prefix": "Heavy", "description": "Weighted strikes.", "damage": 2, "accuracy": -1, "defense": 0},
    {"id": "affix_quickdraw", "name_prefix": "Quickdraw", "description": "Fast presentation.", "damage": 0, "accuracy": 2, "defense": 0},
    {"id": "affix_insulated", "name_prefix": "Insulated", "description": "Resists steam burns.", "damage": 0, "accuracy": 0, "defense": 1},
    {"id": "affix_poisoned", "name_prefix": "Poisoned", "description": "Coated with tunnel venom.", "damage": 1, "accuracy": 0, "defense": 0},
    {"id": "affix_steamcharged", "name_prefix": "Steam-Charged", "description": "Vents heat on impact.", "damage": 1, "accuracy": 0, "defense": 0},
    {"id": "affix_riveted", "name_prefix": "Riveted", "description": "Extra rivets hold plates firm.", "damage": 0, "accuracy": 0, "defense": 3},
    {"id": "affix_serrated", "name_prefix": "Serrated", "description": "Tearing edge.", "damage": 1, "accuracy": 2, "defense": 0},
    {"id": "affix_padded", "name_prefix": "Padded", "description": "Soft lining absorbs blows.", "damage": 0, "accuracy": 0, "defense": 1},
    {"id": "affix_occultbound", "name_prefix": "Occult-Bound", "description": "Whispers along the sight line.", "damage": 1, "accuracy": 2, "defense": 0},
    {"id": "affix_calibrated", "name_prefix": "Calibrated", "description": "Precision-machined components.", "damage": 0, "accuracy": 4, "defense": 0},
]

RECIPES: list[dict[str, Any]] = [
    {
        "id": "recipe_reinforced_wrench",
        "name": "Reinforce Wrench",
        "station": "forge",
        "skill_required": "skill_smithing",
        "skill_rank": 1,
        "engineering_required": 2,
        "ingredients": [{"item_id": "item_wrench", "count": 1}, {"item_id": "item_scrap", "count": 2}],
        "result_id": "item_reinforced_wrench",
    },
    {
        "id": "recipe_calibrated_pepperbox",
        "name": "Calibrate Pepperbox",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 2,
        "engineering_required": 3,
        "ingredients": [{"item_id": "item_pepperbox", "count": 1}, {"item_id": "item_scrap", "count": 1}, {"item_id": "item_machine_oil", "count": 1}],
        "result_id": "item_calibrated_pepperbox",
    },
    {
        "id": "recipe_filter_mask",
        "name": "Assemble Filter Mask",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 1,
        "engineering_required": 1,
        "ingredients": [{"item_id": "item_scrap", "count": 2}, {"item_id": "item_machine_oil", "count": 1}],
        "result_id": "item_filter_mask",
    },
    {
        "id": "recipe_brass_plate",
        "name": "Forge Brass Plate",
        "station": "forge",
        "skill_required": "skill_smithing",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_brass_ingot", "count": 2}, {"item_id": "item_leather", "count": 1}, {"item_id": "item_coal", "count": 1}],
        "result_id": "item_brass_plate",
    },
    {
        "id": "recipe_brass_helm",
        "name": "Forge Brass Helm",
        "station": "forge",
        "skill_required": "skill_smithing",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_brass_ingot", "count": 1}, {"item_id": "item_scrap", "count": 1}],
        "result_id": "item_brass_helm",
    },
    {
        "id": "recipe_warhammer",
        "name": "Forge Warhammer",
        "station": "forge",
        "skill_required": "skill_smithing",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_scrap", "count": 3}, {"item_id": "item_coal", "count": 2}, {"item_id": "item_wire", "count": 1}],
        "result_id": "item_warhammer",
    },
    {
        "id": "recipe_steam_axe",
        "name": "Assemble Steam Axe",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 3,
        "ingredients": [{"item_id": "item_scrap", "count": 2}, {"item_id": "item_gears", "count": 2}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_steam_axe",
    },
    {
        "id": "recipe_rifle",
        "name": "Assemble Rifle",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_scrap", "count": 2}, {"item_id": "item_wire", "count": 2}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_rifle",
    },
    {
        "id": "recipe_shotgun",
        "name": "Assemble Shotgun",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_scrap", "count": 3}, {"item_id": "item_wire", "count": 1}],
        "result_id": "item_shotgun",
    },
    {
        "id": "recipe_arc_pistol",
        "name": "Bind Arc Pistol",
        "station": "workbench",
        "skill_required": "skill_occult",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_pepperbox", "count": 1}, {"item_id": "item_crystal", "count": 1}, {"item_id": "item_wire", "count": 2}],
        "result_id": "item_arc_pistol",
    },
    {
        "id": "recipe_rifle_ammo",
        "name": "Pack Rifle Cartridges",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_scrap", "count": 1}, {"item_id": "item_sulfur", "count": 1}, {"item_id": "item_coal", "count": 1}],
        "result_id": "item_rifle_ammo",
    },
    {
        "id": "recipe_shot_shells",
        "name": "Load Shot Shells",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_scrap", "count": 1}, {"item_id": "item_sulfur", "count": 2}],
        "result_id": "item_shot_shells",
    },
    {
        "id": "recipe_arc_cells",
        "name": "Charge Arc Cells",
        "station": "workbench",
        "skill_required": "skill_occult",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_crystal", "count": 1}, {"item_id": "item_wire", "count": 1}],
        "result_id": "item_arc_cell",
    },
    {
        "id": "recipe_healing_salve",
        "name": "Brew Healing Salve",
        "station": "alchemy",
        "skill_required": "skill_medicine",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_herbs", "count": 2}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_healing_salve",
    },
    {
        "id": "recipe_antidote",
        "name": "Distill Antidote",
        "station": "alchemy",
        "skill_required": "skill_medicine",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_herbs", "count": 3}, {"item_id": "item_sulfur", "count": 1}],
        "result_id": "item_antidote_vial",
    },
    {
        "id": "recipe_combat_stim",
        "name": "Mix Combat Stim",
        "station": "alchemy",
        "skill_required": "skill_medicine",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_herbs", "count": 1}, {"item_id": "item_sulfur", "count": 1}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_combat_stim",
    },
    {
        "id": "recipe_smoke_bomb",
        "name": "Pack Smoke Bomb",
        "station": "alchemy",
        "skill_required": "skill_engineering",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_sulfur", "count": 2}, {"item_id": "item_scrap", "count": 1}],
        "result_id": "item_smoke_bomb",
    },
    {
        "id": "recipe_leather_coat",
        "name": "Stitch Leather Coat",
        "station": "workbench",
        "skill_required": "skill_smithing",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_leather", "count": 3}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_leather_coat",
    },
    {
        "id": "recipe_steam_vest",
        "name": "Insulate Steam Vest",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 2,
        "ingredients": [{"item_id": "item_leather", "count": 2}, {"item_id": "item_gears", "count": 1}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_steam_vest",
    },
    {
        "id": "recipe_brass_ingot",
        "name": "Smelt Brass Ingot",
        "station": "forge",
        "skill_required": "skill_smithing",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_scrap", "count": 3}, {"item_id": "item_coal", "count": 2}],
        "result_id": "item_brass_ingot",
    },
    {
        "id": "recipe_machine_oil",
        "name": "Refine Machine Oil",
        "station": "alchemy",
        "skill_required": "skill_engineering",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_oil_can", "count": 1}, {"item_id": "item_herbs", "count": 1}],
        "result_id": "item_machine_oil",
    },
    {
        "id": "recipe_padded_gauntlets",
        "name": "Pad Gauntlets",
        "station": "workbench",
        "skill_required": "skill_smithing",
        "skill_rank": 1,
        "ingredients": [{"item_id": "item_leather", "count": 2}, {"item_id": "item_scrap", "count": 1}],
        "result_id": "item_padded_gauntlets",
    },
    {
        "id": "recipe_steam_treads",
        "name": "Fit Steam Treads",
        "station": "workbench",
        "skill_required": "skill_engineering",
        "skill_rank": 3,
        "ingredients": [{"item_id": "item_iron_boots", "count": 1}, {"item_id": "item_gears", "count": 2}, {"item_id": "item_oil_can", "count": 1}],
        "result_id": "item_steam_treads",
    },
]

MONSTERS: list[dict[str, Any]] = [
    {
        "id": "mon_gear_rat",
        "name": "Gear Rat",
        "description": "Scrabbling rodent with cog-teeth that chews through cable.",
        "hp": 8,
        "melee_accuracy": 45,
        "melee_damage": 2,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 0,
        "behavior": "melee_pursuer",
        "vision": 6,
        "hear_radius": 4,
        "abilities": ["melee"],
        "drop_item_id": "item_scrap",
        "xp": 12,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["mine", "machine"],
    },
    {
        "id": "mon_clockwork_sentry",
        "name": "Clockwork Sentry",
        "description": "Tripod-mounted automaton guarding forge corridors.",
        "hp": 12,
        "melee_accuracy": 35,
        "melee_damage": 2,
        "ranged_accuracy": 50,
        "ranged_damage": 3,
        "defense": 1,
        "behavior": "ranged_sentry",
        "vision": 7,
        "hear_radius": 5,
        "abilities": ["ranged"],
        "drop_item_id": "item_ball_ammo",
        "xp": 20,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry", "machine"],
    },
    {
        "id": "mon_steam_wraith",
        "name": "Steam Wraith",
        "description": "Condensed vapor spirit that spews caustic mist.",
        "hp": 10,
        "melee_accuracy": 40,
        "melee_damage": 1,
        "ranged_accuracy": 48,
        "ranged_damage": 2,
        "defense": 0,
        "behavior": "poison_spitter",
        "vision": 6,
        "hear_radius": 3,
        "abilities": ["poison_spit"],
        "drop_item_id": "item_machine_oil",
        "xp": 18,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry", "occult"],
    },
    {
        "id": "mon_brass_golem",
        "name": "Brass Golem",
        "description": "Slow plated construct that holds choke points.",
        "hp": 22,
        "melee_accuracy": 42,
        "melee_damage": 4,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 4,
        "behavior": "defensive",
        "vision": 5,
        "hear_radius": 4,
        "abilities": ["melee"],
        "drop_item_id": "item_brass_ingot",
        "xp": 35,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry"],
    },
    {
        "id": "mon_scrap_hound",
        "name": "Scrap Hound",
        "description": "Pack hunter assembled from junk and spite.",
        "hp": 9,
        "melee_accuracy": 50,
        "melee_damage": 2,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 0,
        "behavior": "pack",
        "vision": 7,
        "hear_radius": 6,
        "abilities": ["melee"],
        "drop_item_id": "item_scrap",
        "xp": 14,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["mine"],
    },
    {
        "id": "mon_tunnel_leech",
        "name": "Tunnel Leech",
        "description": "Cowardly parasite that flees after a single bite.",
        "hp": 6,
        "melee_accuracy": 38,
        "melee_damage": 1,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 0,
        "behavior": "flee",
        "vision": 5,
        "hear_radius": 5,
        "abilities": ["melee"],
        "drop_item_id": "item_herbs",
        "xp": 8,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["mine"],
    },
    {
        "id": "mon_acid_sprayer",
        "name": "Acid Sprayer",
        "description": "Rusted boiler on legs that vents corrosive spray.",
        "hp": 14,
        "melee_accuracy": 30,
        "melee_damage": 1,
        "ranged_accuracy": 46,
        "ranged_damage": 3,
        "defense": 1,
        "behavior": "poison_spitter",
        "vision": 6,
        "hear_radius": 4,
        "abilities": ["poison_spit"],
        "drop_item_id": "item_sulfur",
        "xp": 22,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry"],
    },
    {
        "id": "mon_pressure_valve",
        "name": "Pressure Valve",
        "description": "Overcharged tank that bursts steam when cornered.",
        "hp": 11,
        "melee_accuracy": 35,
        "melee_damage": 2,
        "ranged_accuracy": 40,
        "ranged_damage": 2,
        "defense": 0,
        "behavior": "steam_burster",
        "vision": 5,
        "hear_radius": 3,
        "abilities": ["steam_burst"],
        "drop_item_id": "item_coal",
        "xp": 20,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry", "machine"],
    },
    {
        "id": "mon_nightmare_lamp",
        "name": "Nightmare Lamp",
        "description": "Flickering occult lantern that projects waking terror.",
        "hp": 9,
        "melee_accuracy": 30,
        "melee_damage": 1,
        "ranged_accuracy": 44,
        "ranged_damage": 1,
        "defense": 0,
        "behavior": "fearer",
        "vision": 8,
        "hear_radius": 2,
        "abilities": ["ranged"],
        "drop_item_id": "item_crystal",
        "xp": 24,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry", "occult"],
    },
    {
        "id": "mon_repair_drone",
        "name": "Repair Drone",
        "description": "Maintenance bot that patches nearby constructs mid-fight.",
        "hp": 10,
        "melee_accuracy": 32,
        "melee_damage": 1,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 1,
        "behavior": "repairer",
        "vision": 6,
        "hear_radius": 5,
        "abilities": ["melee"],
        "drop_item_id": "item_gears",
        "xp": 16,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["foundry", "machine"],
    },
    {
        "id": "mon_bell_summoner",
        "name": "Bell Summoner",
        "description": "Cultist automaton that rings a brass bell to call allies.",
        "hp": 13,
        "melee_accuracy": 36,
        "melee_damage": 2,
        "ranged_accuracy": 0,
        "ranged_damage": 0,
        "defense": 1,
        "behavior": "summoner",
        "vision": 7,
        "hear_radius": 8,
        "abilities": ["melee"],
        "drop_item_id": "item_wire",
        "xp": 26,
        "is_elite": False,
        "is_boss": False,
        "theme_tags": ["occult", "foundry"],
    },
    {
        "id": "mon_veteran_sentry",
        "name": "Veteran Sentry",
        "description": "Battle-scarred elite automaton with reinforced plating.",
        "hp": 20,
        "melee_accuracy": 48,
        "melee_damage": 4,
        "ranged_accuracy": 55,
        "ranged_damage": 4,
        "defense": 3,
        "behavior": "elite",
        "vision": 8,
        "hear_radius": 6,
        "abilities": ["melee", "ranged"],
        "drop_item_id": "item_rifle_ammo",
        "xp": 45,
        "is_elite": True,
        "is_boss": False,
        "theme_tags": ["foundry", "machine"],
    },
    {
        "id": "mon_forge_titan",
        "name": "Forge Titan",
        "description": "Colossal boiler-golem that rules the deepest foundry.",
        "hp": 80,
        "melee_accuracy": 55,
        "melee_damage": 8,
        "ranged_accuracy": 50,
        "ranged_damage": 5,
        "defense": 6,
        "behavior": "boss",
        "vision": 10,
        "hear_radius": 10,
        "abilities": ["melee", "steam_burst", "ranged"],
        "drop_item_id": "item_steam_axe",
        "xp": 200,
        "is_elite": False,
        "is_boss": True,
        "theme_tags": ["foundry", "boss"],
    },
]

MERCHANTS: list[dict[str, Any]] = [
    {
        "id": "merchant_general",
        "name": "General Trader",
        "inventory": [
            {"item_id": "item_field_ration", "count": 5, "price": 4},
            {"item_id": "item_scrap", "count": 10, "price": 3},
            {"item_id": "item_oil_can", "count": 3, "price": 5},
            {"item_id": "item_coal", "count": 6, "price": 3},
            {"item_id": "item_work_gloves", "count": 1, "price": 8},
            {"item_id": "item_soft_shoes", "count": 1, "price": 10},
            {"item_id": "item_leather", "count": 4, "price": 5},
        ],
        "buy_rate": 0.4,
        "sell_rate": 1.0,
        "restock_on_depth": True,
    },
    {
        "id": "merchant_arms",
        "name": "Arms Dealer",
        "inventory": [
            {"item_id": "item_pepperbox", "count": 1, "price": 25},
            {"item_id": "item_cutlass", "count": 1, "price": 22},
            {"item_id": "item_ball_ammo", "count": 24, "price": 20},
            {"item_id": "item_rifle_ammo", "count": 12, "price": 18},
            {"item_id": "item_brass_helm", "count": 1, "price": 20},
            {"item_id": "item_iron_boots", "count": 1, "price": 18},
            {"item_id": "item_engineer_goggles", "count": 1, "price": 16},
        ],
        "buy_rate": 0.35,
        "sell_rate": 1.15,
        "restock_on_depth": True,
    },
    {
        "id": "merchant_healer",
        "name": "Field Medic",
        "inventory": [
            {"item_id": "item_healing_salve", "count": 4, "price": 8},
            {"item_id": "item_machine_oil", "count": 3, "price": 6},
            {"item_id": "item_antidote_vial", "count": 3, "price": 10},
            {"item_id": "item_combat_stim", "count": 2, "price": 14},
            {"item_id": "item_herbs", "count": 6, "price": 4},
            {"item_id": "item_filter_mask", "count": 1, "price": 15},
        ],
        "buy_rate": 0.45,
        "sell_rate": 0.95,
        "restock_on_depth": False,
    },
]

ENVIRONMENTS: list[dict[str, Any]] = [
    {
        "id": "env_foundry",
        "name": "Foundry Depths",
        "description": "Roaring furnaces, steam vents, and molten runoff.",
        "palette": {"floor": "#3a2a22", "wall": "#5c4030", "accent": "#c45a1a", "fog": "#2a1a12"},
        "hazard_chance": 0.18,
        "monster_tags": ["foundry", "machine", "occult"],
        "ambient": "steam_hiss",
    },
    {
        "id": "env_mine",
        "name": "Collapsed Mine",
        "description": "Timbered tunnels, cave-ins, and flooded shafts.",
        "palette": {"floor": "#2a2e32", "wall": "#4a5058", "accent": "#6a7a88", "fog": "#1a1e22"},
        "hazard_chance": 0.12,
        "monster_tags": ["mine", "machine"],
        "ambient": "drip_echo",
    },
]

# Obsolete filenames to remove after generation (superseded ids/slots).
OBSOLETE_FILES: dict[str, list[str]] = {
    "skills": ["ranged.json"],
}

# Filename stem overrides when id prefix does not map cleanly.
FILENAME_OVERRIDES: dict[str, str] = {
    "race_human": "human",
    "race_automaton": "automaton",
    "race_dwarf": "dwarf",
    "race_elf": "elf",
    "race_gnome": "gnome",
    "race_beastfolk": "beastfolk",
    "class_adventurer": "adventurer",
    "class_engineer": "engineer",
    "class_gunslinger": "gunslinger",
    "class_occultist": "occultist",
    "class_officer": "officer",
    "class_scoundrel": "scoundrel",
    "skill_melee": "melee",
    "skill_marksmanship": "marksmanship",
    "skill_defense": "defense",
    "skill_engineering": "engineering",
    "skill_smithing": "smithing",
    "skill_medicine": "medicine",
    "skill_stealth": "stealth",
    "skill_occult": "occult",
    "env_foundry": "foundry",
    "env_mine": "mine",
    "merchant_general": "general",
    "merchant_arms": "arms",
    "merchant_healer": "healer",
}


def _filename_for(entry: dict[str, Any]) -> str:
    eid = entry["id"]
    if eid in FILENAME_OVERRIDES:
        return FILENAME_OVERRIDES[eid]
    # item_wrench -> wrench, mon_gear_rat -> gear_rat, recipe_x -> x
    for prefix in ("item_", "mon_", "recipe_", "affix_"):
        if eid.startswith(prefix):
            return eid[len(prefix) :]
    return eid


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _write_folder(folder: str, entries: list[dict[str, Any]]) -> int:
    out_dir = CONTENT / folder
    out_dir.mkdir(parents=True, exist_ok=True)
    for obsolete in OBSOLETE_FILES.get(folder, []):
        obs_path = out_dir / obsolete
        if obs_path.exists():
            obs_path.unlink()
    count = 0
    for entry in entries:
        fname = f"{_filename_for(entry)}.json"
        _write_json(out_dir / fname, entry)
        count += 1
    return count


def main() -> None:
    folders: list[tuple[str, list[dict[str, Any]]]] = [
        ("races", RACES),
        ("classes", CLASSES),
        ("skills", SKILLS),
        ("items", ITEMS),
        ("affixes", AFFIXES),
        ("recipes", RECIPES),
        ("monsters", MONSTERS),
        ("merchants", MERCHANTS),
        ("environments", ENVIRONMENTS),
    ]

    print("Brassdeep Phase 2 content generation")
    print("=" * 40)
    total = 0
    for folder, entries in folders:
        n = _write_folder(folder, entries)
        total += n
        print(f"  {folder:14s} {n:3d} files")
    print("=" * 40)
    print(f"  {'TOTAL':14s} {total:3d} files")
    print(f"Content root: {CONTENT}")


if __name__ == "__main__":
    main()
